### ISSUE TITLE
Build iOS app

### ISSUE THREAD

**Issue by shekohex** [sunshine-protocol/sunshine-identity-ui#4]
Currently, we had issues to build our app into iOS targets, see #1 for more info.

So here is what I tried and it _worked for now_

0. Start Clean :)
```bash
$ git clone https://github.com/sunshine-protocol/sunshine-identity-ui.git
```
1. Clone [sysinfo](https://github.com/GuillaumeGomez/sysinfo) locally 
```bash
$ git clone https://github.com/GuillaumeGomez/sysinfo.git
```
2. Edit `sysinfo` version (downgrade)
```diff
 [package]
 name = "sysinfo"
-version = "0.14.14"
+version = "0.13.14"
```
3. Patch our `Cargo.toml` files

Path: `./Cargo.toml`
```toml
[patch.crates-io]
netstat2 = { git = "https://github.com/shekohex/netstat2-rs/", branch = "ios-support" }
sysinfo = { path = "../sysinfo" } # local sysinfo for testing
```

Path: `./native/identity-client/Cargo.toml`
```toml
[dependencies]
# we don't use it in code directly..
ed25519-dalek = "=1.0.0-pre.3" # prevent update of ed25519-dalek
```
and Run `cargo update` after that (**IMPORTANT**).

4. Build The Project using cargo make

```bash
$ cargo make ios-release --profile release
```
that would take a while, get you a cup of coffee or watch a [Netflix Movie](https://www.digitaltrends.com/movies/best-movies-on-netflix/) ;)

okay, after that, Run
```bash
$ cargo make post-ios --profile release
```
5. Build the flutter App
This a sanity check step, to make sure it builds as an iOS app and links everything together.
```bash
$ flutter build -v ios --simulator
```
6. Run it
start an iOS simulator `open -a simulator` and
```bash
$ flutter run
```

That's it, hope it works for you too.
